### ISSUE TITLE
LSP: OpenGOAL Language Feature TODO List

### ISSUE THREAD

**Issue by xTVaser** [open-goal/opengoal-vscode#256]
Fairly easy
- [ ] Go to Declaration
- [ ] Go to Definition
- [ ] Go to Type Definition
- [ ] Go to Implementation
- [ ] Find References
- [ ] Prepare Type Hierarchy
- [ ] Type Hierarchy Super Types
- [ ] Type Hierarchy Sub Types
- [ ] Hover
- [ ] Document Symbols
- [ ] Inline Value
- [ ] Inline Value Refresh
- [ ] Status from LSP
  - https://github.com/rust-lang/rust-analyzer/commit/3ef76760761d17cef4ea4e8462d9ee2ca8395467#diff-bca0ed357f47caaadd008edc9b2df19f36869583b78c2c0265b9f0db3650df2e
- [ ] Publish Diagnostics
- [ ] Pull Diagnostics
- [ ] Signature Help
- [ ] Document Color

AST Needed
- [ ] Completion Proposals
- [ ] Completion Item Resolve
- [ ] Folding Range
- [ ] Semantic Tokens
- [ ] Document Highlight
- [ ] Formatting
- [ ] Range Formatting
- [ ] Rename
- [ ] Prepare Rename

Project Wide Parsing
- [ ] Prepare Call Hierarchy
- [ ] Call Hierarchy Incoming Calls
- [ ] Call Hierarchy Outgoing Calls

Would be nice, but not sure what I'd use it for yet
- [ ] Code Lens
  - [ ] Compile Form?
- [ ] Code Lens Refresh
- [ ] Document Link
- [ ] Document Link Resolve
- [ ] Code Action
- [ ] Code Action Resolve
- [ ] On type Formatting

Probably Won't Do
- [ ] Moniker
- [ ] Selection Range
- [ ] Inlay Hint
- [ ] Inlay Hint Resolve
- [ ] Inlay Hint Refresh
- [ ] Color Presentation
- [ ] Linked Editing Range
